- type: replace
  path: /releases/-
  value:
    name: bpm
    version: 0.2.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.2.0
    sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54

- type: replace
  path: /releases/-
  value:
    name: zookeeper
    version: 0.0.7
    url: https://bosh.io/d/github.com/cppforlife/zookeeper-release?v=0.0.7
    sha1: a863ef216ea75d22950703a3c924959cb20e59ba

- type: replace
  path: /releases/-
  value:
    name: kafka
    version: 1.1.3-govau-tls
    url:  https://github.com/govau/kafka-boshrelease/releases/download/v1.1.3-govau-tls/kafka-1.1.3-govau-tls.tgz
    sha1: 7598927e0bf8e2bcfadcd27184dd4d737fdfe876

- type: replace
  path: /instance_groups/-
  value:
    name: zookeeper
    azs: [z1, z2, z3]
    instances: 3
    jobs:
    - name: bpm
      release: bpm
    - name: zookeeper
      release: zookeeper
      properties: {}
    - name: status
      release: zookeeper
      properties: {}
    vm_type: minimal
    stemcell: default
    persistent_disk: 10240
    networks:
    - name: default

- type: replace
  path: /instance_groups/-
  value:
    name: kafka
    azs: [z1, z2, z3]
    instances: 3
    jobs:
    - name: consul_agent
      release: consul
      consumes:
        consul_common: {from: consul_common_link}
        consul_server: nil
        consul_client: {from: consul_client_link}
      properties:
        consul:
          agent:
            services:
              kafka:
                name: kafka
                check: {} # TODO, healthcheck
    - name: bpm
      release: bpm
    - name: kafka
      release: kafka
      properties:
        dns_suffix: kafka.service.cf.internal
        tls:
          ca_certs:
          - ((kafka-ca.certificate))
          certificate: ((kafka-broker))
    - name: kafka-firehose-nozzle
      release: kafka
      properties:
        cf:
          subscription_id: kafka-firehose-nozzle
          doppler_address: wss://doppler.((system_domain)):4443
        uaa:
          url: https://uaa.((system_domain))
          client_id: kafka-firehose-nozzle
          client_secret: ((kafka-firehose-nozzle-client-secret))
        kafka:
          client_certificate: ((kafka-firehose-nozzle-kafka-certificate))
          server_ca_certificates:
          - ((kafka-ca.certificate))
    vm_type: minimal
    stemcell: default
    persistent_disk: 10240
    networks:
    - name: default

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/kafka-firehose-nozzle?
  value:
    authorized-grant-types: client_credentials
    authorities: doppler.firehose
    secret: "((kafka-firehose-nozzle-client-secret))"

- type: replace
  path: /variables/-
  value:
    name: kafka-firehose-nozzle-client-secret
    type: password

- type: replace
  path: /variables/-
  value:
    name: kafka-ca
    type: certificate
    options:
      is_ca: true
      common_name: kafka

- type: replace
  path: /variables/-
  value:
    name: kafka-broker
    type: certificate
    options:
      ca: kafka-ca
      common_name: kafka.service.cf.internal
      alternative_names:
      - "*.kafka.service.cf.internal"
      - "*.kafka.default.kafka.bosh"
      extended_key_usage:
      - client_auth
      - server_auth

- type: replace
  path: /variables/-
  value:
    name: kafka-firehose-nozzle-kafka-certificate
    type: certificate
    options:
      ca: kafka-ca
      common_name: kafka-firehose-nozzle
      extended_key_usage:
      - client_auth
