addons:
- jobs:
  - name: bpm
    release: bpm
  name: bpm
instance_groups:
- azs:
  - z1
  - z2
  - z3
  instances: 1
  jobs:
  - name: kafka-manager
    properties:
      password: OMGIDIDATHING
      username: admin
    release: kafka_2.4.1
  name: kafka-manager
  networks:
  - name: default
  persistent_disk_type: 10GB
  stemcell: default
  vm_type: c4.large
- azs:
  - z1
  - z2
  - z3
  instances: 3
  jobs:
  - name: zookeeper
    properties: {}
    release: zookeeper
  - name: status
    properties: {}
    release: zookeeper
  name: zookeeper
  networks:
  - name: default
  persistent_disk_type: 10GB
  stemcell: default
  vm_type: c4.large
- azs:
  - z1
  - z2
  - z3
  instances: 3
  jobs:
  - name: kafka
    properties:
      bpm:
        limits:
          memory: 8GB
          open_files: 128000
      jmx_port: 9090
      kafka:
        jmx:
          opts: "-Dcom.sun.management.jmxremote \\\n-Dcom.sun.management.jmxremote.local.only=false
            \\\n-Dcom.sun.management.jmxremote.authenticate=false \\\n-Dcom.sun.management.jmxremote.ssl=false
            \         \n"
          port: 9090
      rack_id: az
      topics:
      - name: Reindex
        partitions: 8
        replication_factor: 3
      - name: cephboot
        partitions: 8
        replication_factor: 3
      - name: cephbootsec
        partitions: 8
        replication_factor: 3
      - name: drPriPrimary
        partitions: 16
        replication_factor: 3
      - name: drPriSecondary
        partitions: 16
        replication_factor: 3
      - name: drSeqPrimary
        partitions: 16
        replication_factor: 3
      - name: drSeqSecondary
        partitions: 16
        replication_factor: 3
      - name: errorMetrics
        partitions: 8
        replication_factor: 3
      - name: export
        partitions: 8
        replication_factor: 3
      - name: exportArchiveLargeTopic
        partitions: 16
        replication_factor: 3
      - name: exportArchiveMediumLargeTopic
        partitions: 16
        replication_factor: 3
      - name: exportArchiveMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportArchivePriorityTopic
        partitions: 8
        replication_factor: 3
      - name: exportArchiveSmallMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportArchiveSmallTopic
        partitions: 8
        replication_factor: 3
      - name: exportEdiscoveryLargeTopic
        partitions: 16
        replication_factor: 3
      - name: exportEdiscoveryMediumLargeTopic
        partitions: 16
        replication_factor: 3
      - name: exportEdiscoveryMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportEdiscoveryPriorityTopic
        partitions: 8
        replication_factor: 3
      - name: exportEdiscoverySmallMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportEdiscoverySmallTopic
        partitions: 8
        replication_factor: 3
      - name: exportMsgNonEmailLargeTopic
        partitions: 8
        replication_factor: 3
      - name: exportMsgNonEmailMediumLargeTopic
        partitions: 8
        replication_factor: 3
      - name: exportMsgNonEmailMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportMsgNonEmailPriorityTopic
        partitions: 8
        replication_factor: 3
      - name: exportMsgNonEmailSmallMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportMsgNonEmailSmallTopic
        partitions: 8
        replication_factor: 3
      - name: exportPriorityTopic
        partitions: 8
        replication_factor: 3
      - name: exportSupervisionLargeTopic
        partitions: 16
        replication_factor: 3
      - name: exportSupervisionMediumLargeTopic
        partitions: 16
        replication_factor: 3
      - name: exportSupervisionMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportSupervisionPriorityTopic
        partitions: 8
        replication_factor: 3
      - name: exportSupervisionSmallMediumTopic
        partitions: 8
        replication_factor: 3
      - name: exportSupervisionSmallTopic
        partitions: 8
        replication_factor: 3
      - name: holdLargeTopic
        partitions: 16
        replication_factor: 3
      - name: holdMediumTopic
        partitions: 8
        replication_factor: 3
      - name: holdSmalTopic
        partitions: 8
        replication_factor: 3
      - name: jobs
        partitions: 8
        replication_factor: 3
      - name: largeHoldTagTopic
        partitions: 16
        replication_factor: 3
      - name: largemsg
        partitions: 16
        replication_factor: 3
      - name: lfs
        partitions: 8
        replication_factor: 3
      - name: mediumHoldTagTopic
        partitions: 8
        replication_factor: 3
      - config: retention.ms=7776000000
        name: purge
        partitions: 16
        replication_factor: 3
      - name: refreshIndexJobs
        partitions: 8
        replication_factor: 3
      - name: reindex
        partitions: 16
        replication_factor: 3
      - name: reindexMetrics
        partitions: 8
        replication_factor: 3
      - name: rs1
        partitions: 16
        replication_factor: 3
      - name: smallHoldTagTopic
        partitions: 8
        replication_factor: 3
      - name: supervision
        partitions: 3
        replication_factor: 3
      - name: supervisionLargeTopic
        partitions: 16
        replication_factor: 3
      - name: supervisionMediumTopic
        partitions: 8
        replication_factor: 3
      - name: supervisionSmalTopic
        partitions: 8
        replication_factor: 3
      - name: supervisionlargeHoldTagTopic
        partitions: 16
        replication_factor: 3
      - name: supervisionmediumHoldTagTopic
        partitions: 8
        replication_factor: 3
      - name: supervisionsmallHoldTagTopic
        partitions: 8
        replication_factor: 3
    release: kafka_2.4.1
  name: kafka
  networks:
  - name: default
  persistent_disk_type: 100GB
  stemcell: default
  vm_type: c4.large
name: dataservices-kafka-test
releases:
- name: bpm
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 0.2.0
- name: zookeeper
  url: git+https://github.com/cppforlife/zookeeper-release
  version: 0.0.7
- name: kafka_2.4.1
  version: 0.1.6
- name: datadog-agent
  version: 2.7.6100
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000
variables: []
